/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories/$categoryId'
import { Route as CartCartcodeRouteImport } from './routes/cart/$cartcode'
import { Route as AuthenticationSignin_jwt_googleRouteImport } from './routes/_authentication/signin_jwt_google'
import { Route as AuthenticationRegisterRouteImport } from './routes/_authentication/register'
import { Route as AuthenticationLogoutRouteImport } from './routes/_authentication/logout'
import { Route as AuthenticationLoginRouteImport } from './routes/_authentication/login'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CartCartcodeRoute = CartCartcodeRouteImport.update({
  id: '/cart/$cartcode',
  path: '/cart/$cartcode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationSignin_jwt_googleRoute =
  AuthenticationSignin_jwt_googleRouteImport.update({
    id: '/_authentication/signin_jwt_google',
    path: '/signin_jwt_google',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationRegisterRoute = AuthenticationRegisterRouteImport.update({
  id: '/_authentication/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationLogoutRoute = AuthenticationLogoutRouteImport.update({
  id: '/_authentication/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/_authentication/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof AuthenticationLoginRoute
  '/logout': typeof AuthenticationLogoutRoute
  '/register': typeof AuthenticationRegisterRoute
  '/signin_jwt_google': typeof AuthenticationSignin_jwt_googleRoute
  '/cart/$cartcode': typeof CartCartcodeRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/cart': typeof CartIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof AuthenticationLoginRoute
  '/logout': typeof AuthenticationLogoutRoute
  '/register': typeof AuthenticationRegisterRoute
  '/signin_jwt_google': typeof AuthenticationSignin_jwt_googleRoute
  '/cart/$cartcode': typeof CartCartcodeRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/cart': typeof CartIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authentication/login': typeof AuthenticationLoginRoute
  '/_authentication/logout': typeof AuthenticationLogoutRoute
  '/_authentication/register': typeof AuthenticationRegisterRoute
  '/_authentication/signin_jwt_google': typeof AuthenticationSignin_jwt_googleRoute
  '/cart/$cartcode': typeof CartCartcodeRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/cart/': typeof CartIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes'
    | '/profile'
    | '/login'
    | '/logout'
    | '/register'
    | '/signin_jwt_google'
    | '/cart/$cartcode'
    | '/categories/$categoryId'
    | '/products/$slug'
    | '/cart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes'
    | '/profile'
    | '/login'
    | '/logout'
    | '/register'
    | '/signin_jwt_google'
    | '/cart/$cartcode'
    | '/categories/$categoryId'
    | '/products/$slug'
    | '/cart'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/notes'
    | '/_authenticated/profile'
    | '/_authentication/login'
    | '/_authentication/logout'
    | '/_authentication/register'
    | '/_authentication/signin_jwt_google'
    | '/cart/$cartcode'
    | '/categories/$categoryId'
    | '/products/$slug'
    | '/cart/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationLogoutRoute: typeof AuthenticationLogoutRoute
  AuthenticationRegisterRoute: typeof AuthenticationRegisterRoute
  AuthenticationSignin_jwt_googleRoute: typeof AuthenticationSignin_jwt_googleRoute
  CartCartcodeRoute: typeof CartCartcodeRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CartIndexRoute: typeof CartIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/$cartcode': {
      id: '/cart/$cartcode'
      path: '/cart/$cartcode'
      fullPath: '/cart/$cartcode'
      preLoaderRoute: typeof CartCartcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/signin_jwt_google': {
      id: '/_authentication/signin_jwt_google'
      path: '/signin_jwt_google'
      fullPath: '/signin_jwt_google'
      preLoaderRoute: typeof AuthenticationSignin_jwt_googleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/register': {
      id: '/_authentication/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticationRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/logout': {
      id: '/_authentication/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthenticationLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/login': {
      id: '/_authentication/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationLogoutRoute: AuthenticationLogoutRoute,
  AuthenticationRegisterRoute: AuthenticationRegisterRoute,
  AuthenticationSignin_jwt_googleRoute: AuthenticationSignin_jwt_googleRoute,
  CartCartcodeRoute: CartCartcodeRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CartIndexRoute: CartIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
